### PR TITLE
Prepare 1.0.0

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by vweevers** [comment]
LGTM. Anything missing in `UPGRADING.md`?

**Comment by ralphtheninja** [comment]
> LGTM. Anything missing in UPGRADING.md?

Not that I can think of. We mentioned:

* API changes
* dropped node versions
* removed default encodings and per stream encodings

**Comment by vweevers** [comment]
IMO we're missing:

- `maxBufferLength` behavior changed
- `destroySoon` was removed (we don't have to explain this one, just mention it)

**Comment by ralphtheninja** [comment]
@vweevers Anything else we should finish before releasing 1.0.0?

**Comment by ralphtheninja** [comment]
@vweevers Btw, did you have to enable anything to have coveralls reporting on PRs or does it work out of the box?

**Comment by vweevers** [comment]
> Anything else we should finish before releasing 1.0.0?

I think we're good! 0 open issues, 100% coverage and PR #100 for release 1.0.0 😄 

> Btw, did you have to enable anything to have coveralls reporting on PRs or does it work out of the box?

Enabling the repo in coveralls is enough (and I disabled status comments). I did add a coveralls token to Travis, but I think that can be removed because the parallel build thing didn't work and the token isn't required for anything else.

**Comment by ralphtheninja** [comment]
> I think we're good! 0 open issues, 100% coverage and PR #100 for release 1.0.0 smile

 :goal_net:

**Pull request merged**
